on:
  push:
  pull_request:

jobs:
  nox:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        python:
          - "3.8"
          - "3.9"
          - "3.10"
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: "${{ matrix.python }}"
      - name: Install nox
        run: pip install nox
      - uses: actions/checkout@v3
      - name: Run nox
        run: nox -p ${{ matrix.python }}

  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: pip install poetry && poetry install
      - name: Generate tex output
        run: >
          mtng generate tests/acts_spec.yml --since 2022-08-01 --now 2022-08-17 > fragment.tex
          mtng generate tests/acts_spec.yml --since 2022-08-01 --now 2022-08-17 --full > full.tex
      - uses: actions/upload-artifact@v3
        with:
          name: latex-src
          path: *.tex
    
  compile:
    runs-on: ubuntu-latest
    image: texlive/texlive:latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: latex-src
      - name: Compile latex
        run: latexmk -pdf -output-directory=full full.tex

  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - name: Install black
        run: pip install black
      - name: Run black
        run: black --check .


