on:
  push:
  pull_request:

jobs:
  nox:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        python:
          - "3.8"
          - "3.9"
          - "3.10"
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: "${{ matrix.python }}"
      - name: Install nox
        run: pip install nox
      - uses: actions/checkout@v3
      - name: Run nox
        run: nox -p ${{ matrix.python }}
